name: zen
version: '0.1.0'

dependencies:
- base
- containers
- optparse-applicative
- pandoc
- parallel
- blessings
- regex-compat
- scalpel
- text

executable:
  main: zeno.hs

ghc-options: -threaded
